# Generated by Django 3.1.4 on 2022-06-23 00:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('email_adress', models.EmailField(max_length=150)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('home_adress', models.CharField(max_length=100)),
                ('date_of_employment', models.DateField()),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
